services:
  postgres:
    image: postgres:16-alpine
    container_name: afyalink-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
  server:
    build: ./server
    image: afyalink-hms-server
    container_name: afyalink-server
    environment:
      NODE_ENV: production
      PORT: ${PORT}
      API_VERSION: ${API_VERSION}
      DB_USER: ${DB_USER}
      DB_HOST: postgres
      DB_DATABASE: ${DB_DATABASE}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 5432
      JWT_SECRET: ${JWT_SECRET}
      CLIENT_URL: ${CLIENT_URL}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    restart: unless-stopped

  client:
    build: ./client
    image: afyalink-hms-client
    container_name: afyalink-client
    ports:
      - "8080:80"
    depends_on:
      - server
    restart: unless-stopped
    environment:
      VITE_BACKEND_URL: "http://localhost:${PORT}"

volumes:
  postgres_data: